### ISSUE TITLE
Only few lines visible

### ISSUE THREAD

**Issue by jaume-rodriguez** [daveho/AceGWT#31]
Hi, 

I've been experimenting a strange issue in the Editor. It doesn't happen always, but evey now and then the Editor gets loaded wrongly and only copule of lines are shown:

![image](https://cloud.githubusercontent.com/assets/20400766/26153005/cd217e38-3b09-11e7-8d14-1abee724d5c4.png)

Notice that there's the highlight of the selected line, but no line numbers nor content. From the Java code we can prove that the whole content is there. Is just a visualisation issue. 

Did somebody else experienced the same kind of bug?

Thank you, 
Jaume.

**Comment by ainslec** [comment]
Can you confirm that line 2 is not a long line of text (with a lot of trailing whitespace)?

**Comment by jaume-rodriguez** [comment]
Yes, I can. I the following screenshot you can see the same editor with the same content after scrolling a bit:

![image](https://cloud.githubusercontent.com/assets/20400766/26153189/9a0c04fe-3b0a-11e7-9b4f-7f65e634cfac.png)

In case you want to check it out, this is the way I'm implementing it, pretty simple:

```
        editor = new AceEditor();
        editor.setWidth("100%");
        editor.setHeight("100%");
        codeDisplayPanel.add(editor);
        editor.startEditor();
        editor.setFontSize(14);
        editor.setShowPrintMargin(false);
        editor.setMode(AceEditorMode.XML);
        editor.setTheme(AceEditorTheme.ECLIPSE);
```

Thanks for your quick response!
Jaume.

**Comment by ainslec** [comment]
(if not confidential) Please can you create gist urls of the two documents you provided screenshots for?

https://gist.github.com/

**Comment by jaume-rodriguez** [comment]
I'd prefer not to share the documents, but they are standard XSL documents. Do you think it might be related to the content of the editor? 
Keep in mind that happens 1 out of 2-3 attempts, maybe less. And it can be with the same code.

**Comment by ainslec** [comment]
I would a textual copy of the code that you posted in this thread chain, character for character. I don't wish to approximate your input.  I think it's not confidential as you already stripped out your data. Is it possible?

**Comment by jaume-rodriguez** [comment]
Hi Ainslec, 

Just found the following method in AceEditor.java and think it could help me: 
`	/**
	 * Call this to force the editor contents to be redisplayed.
	 * There seems to be a problem when an AceEditor is embedded in a LayoutPanel:
	 * the editor contents don't appear, and it refuses to accept focus
	 * and mouse events, until the browser window is resized.
	 * Calling this method works around the problem by forcing
	 * the underlying editor to redisplay itself fully. (?)
	 */
	public native void redisplay() /*-{
		var editor = this.@edu.ycp.cs.dh.acegwt.client.ace.AceEditor::editor;
		editor.renderer.onResize(true);
		editor.renderer.updateFull();
		editor.resize();
		editor.focus();
	}-*/;`

I'll try to use it and will post here the results.

**Comment by jaume-rodriguez** [comment]
Hi, 
Just want to confirm that calling the redisplay method did the trick. 
Thanks for your help!
